name: Publish 🚀

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./ECommerce.sln
        
      - name: Build
        run: dotnet build ./ECommerce.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./ECommerce.sln --configuration Release --no-build 
    
